# Site settings
title: "Xin Wang's homepage"
name: "Xin Wang 王鑫"
email: albertfxwang@gmail.com
url: http://www.astro.ucla.edu/~xwang/
description: "This is Xin Wang's Homepage for Astrophysical Research"
keywords: "Astrophysics"
meta_author: Wang Xin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 281e66 #483d8b #4169e1 #132454 #80B3FF, 18bc9c
  primary-rgb: "40,30,102" #"106,90,205" #"65,105,225" #"24,288,156" #"128,179,255"
  secondary: 6757cc #8e9fc9 #FD6E8A
  secondary-dark: 233140 #A2122F
  third: BAC0C7
  #  white: fff
  #  primary: 18bc9c #80B3FF
  #  secondary: 2c3e50 #FD6E8A
  #  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Xin Wang
  location: Los Angeles, CA
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url: https://www.facebook.com/albert.xin.wang
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: http://github.com/albertfxwang

# Postal address (add as many lines as necessary)
address:
  - line: Department of Physics and Astronomy
  - line: University of California, Los Angeles
  - line: Los Angeles, CA 90095-1547, USA

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
credits: 'This website is based on Jekyll theme <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a>.'

# Build settings
markdown: kramdown
permalink: pretty
